"""temp_migration

Revision ID: 9b8ddbae4c17
Revises: 0ed9c7f107d9
Create Date: 2025-03-25 09:10:31.497628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b8ddbae4c17"
down_revision: Union[str, None] = "0ed9c7f107d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("movies", sa.Column("likes", sa.Integer(), nullable=True))
    op.add_column("movies", sa.Column("dislikes", sa.Integer(), nullable=True))
    op.add_column("movies", sa.Column("rate", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "rate")
    op.drop_column("movies", "dislikes")
    op.drop_column("movies", "likes")
    op.drop_table("comments")
    # ### end Alembic commands ###
